name: Build, Push & Deploy
on:
  push:	
    branches:
      - main
  
jobs:
  buildAndDeploy:
    name: Build image and push to GitHub Packages registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build, tag, and push image to Github Container Registry
        run: |
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u vitat --password-stdin
          docker build -t flask-api .
          docker tag flask-api ghcr.io/sejavitat/flask-api
          docker push ghcr.io/andre177/flask-api